perfectcushion/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

perfectcushion/perfectcushion/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('imagefit/', include('imagefit.urls')),
    path('search/', include('search_app.urls')),
    path('cart', include('cart.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

perfectcushion/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
	path('', views.searchResult, name='searchResult'),
]

perfectcushion/shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns= [
	path('',views.allProdCat, name='allProdCat'),
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

perfectcushion/cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
	cart_id = models.CharField(max_length=250, blank=True)
	date_added = models.DateField(auto_now_add=True)
	class Meta:
		db_table = 'Cart'
		ordering = ['date_added']

	def __str__(self):
		return self.cart_id

class CartItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	active = models.BooleanField()
	class Meta:
		db_table = 'CartItem'

	def sub_total(self):
		return self.product.price * self.quantity

	def __str__(self):
		return self.product 

perfectcushion/search_app/models.py
from django.db import models

# Create your models here.

perfectcushion/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=250, unique=True)
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='category', blank=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_url(self):
		return reverse('shop:products_by_category', args=[self.slug])

	def __str__(self):
		return '{}'.format(self.name)

class Product(models.Model):
	name = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=250, unique=True)
	description = models.TextField(blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	image = models.ImageField(upload_to='product', blank=True)
	stock = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'product'
		verbose_name_plural = 'products'

	def get_url(self):
		return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

	def __str__(self):
		return '{}'.format(self.name)

perfectcushion/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        request.session.create()  # it does not return anything. that is why `cart = request.session.create()` will not work
        cart = request.session.session_key
    return cart  # Ultimately return cart

def add_cart(request, product_id):
	product = Product.objects.get(id=product_id)
	try:
		cart = Cart.objects.get(cart_id=_cart_id(request))
	except Cart.DoesNotExist:
		cart = Cart.objects.create(
				cart_id = _cart_id(request)
			)
		cart.save()
	try:
		cart_item = CartItem.objects.get(product=product, cart=cart)
		if cart_item.quantity < cart_item.product.stock:
			cart_item.quantity += 1
		cart_item.save()
	except CartItem.DoesNotExist:
		cart_item = CartItem.objects.create(
					product = product,
					quantity = 1,
					cart = cart
			)
		cart_item.save()
	return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items = None):
	try:
		cart = Cart.objects.get(cart_id=_cart_id(request))
		cart_items = CartItem.objects.filter(cart=cart, active=True)
		for cart_item in cart_items:
			total += (cart_item.product.price * cart_item.quantity)
			counter += cart_item.quantity
	except ObjectDoesNotExist:
		pass

	return render(request, 'cart.html', dict(cart_items, total=total, counter = counter))

def cart_remove(request, product_id):
	cart = Cart.objects.get(cart_id=_cart_id(request))
	product = get_object_or_404(Product, id=product_id)
	cart_item = CartItem.objects.get(product=product, cart=cart)
	if cart_item.quantity > 1:
		cart_item.quantity -= 1
		cart_item.save()
	else:
		cart_item.delete()
	return redirect('cart:cart_detail')

def full_remove(request, product_id):
	cart = Cart.objects.get(cart_id=_cart_id(request))
	product = get_object_or_404(Product, id=product_id)
	cart_item = CartItem.objects.get(product=product, cart=cart)
	cart_item.delete()
	return redirect('cart:cart_detail')

perfectcushion/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(request):
	product=None
	query=None
	if 'q' in request.GET:
		query = request.GET.get('q')
		products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
	return render(request, 'search.html',{'query':query,'products':products})

perfectcushion/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category,Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def index(request):
	text_var = 'This is my Django app web page, we.'
	return HttpResponse(text_var)

#Category view

def allProdCat(request, c_slug=None):
	c_page = None
	products_list = None
	if c_slug!=None:
		c_page = get_object_or_404(Category,slug=c_slug)
		products_list = Product.objects.filter(category=c_page,available=True)
	else:
		products_list = Product.objects.all().filter(available=True)
	'''Pagination code'''
	paginator = Paginator(products_list, 6)
	try:
		page = int(request.GET.get('page','1'))
	except:
		page = 1
	try:
		products = paginator.page(page)
	except (EmptyPage,InvalidPage):
		products = paginator.page(paginator.num_pages)
	return render(request,'shop/category.html',{'category':c_page,'products':products})
	
def ProdCatDetail(request,c_slug, product_slug):
	try:
		product = Product.objects.get(category__slug=c_slug, slug=product_slug)
	except Exception as e:
		raise e 
	return render(request,'shop/product.html',{'product':product})

perfectcushion/cart/templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	This is the shopping cart page. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
	Cart - Perfect Cushion Store
{% endblock %}
{% block content %}
	{% if not cart_items %}
		<div>
			<div class="text-center">
				<br>
				<h1 class="text-center my_title">
					Your shopping cart is empty
				</h1>
				<br>
				<p class="text-center">
					Please click <a href="{% url 'shop:allProdCat' %}">here</a> to continue shopping.
				</p>
			</div>
		</div>
	{% else %}
		<div>
			<div class="text-center">
				<br>
				<h1 class="text-center my_title">
					Your shopping cart
				</h1>
				<br>
			</div>
		</div>
		<div class="row mx-auto">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table my_custom_table">
					<thead class="my_custom_thead">
						<tr>
							<th colspan="5">
								Your items
							</th>
						</tr>
						
					</thead>
					<tbody>
						{% for cart_item in cart_items %}
							<tr>
								<td>
									<a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
								</td>
								<td class="text-left">
									{{cart_item.product.name}}
									<br>
									SKU: {{cart_item.product.id}}
									<br>
									Unit Price: £{{cart_item.product.price}}
									<br>
									Qty: {{cart_item.quantity}} x £{{cart_item.product.price}}
								</td>
								<td>
									£{{cart_item.sub_total}}
								</td>
								{% if cart_item.quantity < cart_item.product.stock %}
									<td>
										<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
									</td>
								{% else %}
									<td>
										&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
									</td>
									<td></td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
			</div>
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table my_custom_table">
					<thead class="my_custom_thead">
						<tr>
							<th>
								Checkout
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Please review your shopping cart items before proceeding with the order payment.
							</td>
						</tr>
						<tr>
							<td class="text-left">
								Your total is: <strong>£{{ total }}</strong>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="mx-auto">
					<form action="" method="POST">
						{% csrf_token %}
					  <script
					    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					    data-key="{{ data_key }}"
					    data-amount="{{ stripe_total }}"
					    data-name="Perfect Cushion Shop"
					    data-description="{{ description }}"
					    data-image="{% static 'img/logo.png' %}"
					    data-locale="auto"
					    data-currency="gbp"
					    data-shipping-address="true"
					    data-billing-address="true"
					    data-zip-code="true">
					  </script>
					</form>
					<a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
				</div>
			</div>
		</div>
		<br>
	{% endif %}
{% endblock %}

perfectcushion/search_app/templates/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	We have a variety of stunning and comfy cushions. Look for the one that suits your needs.
{% endblock %}
{% block title %}
	Search - Perfect Cushion Store
{% endblock %}
{% block content %}
	<div>
		<p class="text-center my_search_text">You have searched for: <b>"{{ query }}"</b></p>
	</div>
		<div class="container">
		<div class="row mx-auto">
			{% for product in products %}
				<div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
					<div class="card text-center" style="min-width: 18rem;">
						<a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
						<div class="card-body">
							<h4>{{product.name}}</h4>
							<p>${{product.price}}</p>
						</div>
					</div>
				</div>
				{% empty %}
				<div class="row mx-auto">
					<p class="text-center my_search_text">0 results found.</p>
				</div>
			{% endfor %}
		</div>
	</div>	
{% endblock %}

perfectcushion/shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html land="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %} {% endblock %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
	<title>{% block title %} {% endblock %} </title>
</head>
<body>
	<div class="container">
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}
	</div>
		{% include 'footer.html' %}
		<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    	<script src="{% static 'js/popper.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

perfectcushion/shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
	<p class="text-center">&copy; Local Game Store - All rights reserved.</p>
</div>

perfectcushion/shop/templates/header.html
{% load staticfiles %}
<header>
	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src ="{% static 'img/logo.png' %}" alt="Perfect Cushion Store">
	</center>
</header>

perfectcushion/shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
        {% for cat in links %}  
          <a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a>
        {% endfor %}  
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-cart-plus">()</i></a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fab fa-searchengin"></i></button>
    </form>
  </div>
</nav>

perfectcushion/shop/templates/shop/category.html
{% extends "base.html" %}
{% load staticfiles %}

{% block metadescription %}
	{% if category %}
		{{ category.description|truncatewords:155 }}
	{% else %}
		Welcome to the cushion store where you can buy comfy and awesome cushions.
	{% endif %}
{% endblock %}
{% block title %}
	{% if category %}
		{{ category.name }} - Perfect Cushion Store
	{% else %}
		See Our Cushion Collection - Perfect Cushion Store
	{% endif %}
{% endblock %}
{% block content %}
		<!--  Breadcrumb navigation  -->
	{% if category %}
			<div class="row my_row_class">
				<div class="mx-auto">
					<p><a href="{% url 'shop:allProdCat' %}">Our Product Collection</a></p>
				</div>
			</div>
	{% endif %}
	<div class="mx-auto">
	{% if category %}
		<img class="my_image" src="{{ category.image.url }}" alt="{{category.name}}">
	</div>
	<br>
	<div>
		<h1 class="text-center my_title">{{category.name}}</h1>
		<p class="text-justify">{{category.description}}</p>
	</div>
	{% else %}
	  	<img class= "my_image my_image_padding" src="{% static 'img/banner.jpg' %}" alt="Our Products Collection">
	</div>
	<br>
	<div>
		<h1 class="text-center my_title">Our Products Collection!!!</h1>
		<p class="text-justify">Finding the perfects cushion for your room can instantly add to the levels of comfort and sense of style throughout your home. They can transform the blandest of decors instantly by adding colour, softness and an air of cosiness. As well as being confy and looking great our range of cushons will comfy and looking great our range of cushions will certainly your decor with personalised charm. </p>
	</div>
	{% endif %}
	<div class="container">
		<div class="row mx-auto">
			{% for product in products.object_list %}
				<div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
					<div class="card text-center" style="min-width: 18rem;">
						<a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}"></a>
						<div class="card-body">
							<h4>{{product.name}}</h4>
							<p>${{product.price}}</p>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		<div class="mx-auto">
			{% if products.paginator.num_pages > 1 %}
				<hr>
				<div class="text-center">
					{% for pg in products.paginator.page_range %}
						<a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
					{% endfor %}
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}

perfectcushion/shop/templates/shop/product.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
	{{ product.name }} - Perfect Cushion Store
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
		<div class="mx-auto">
			<p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{product.name}}</p>
		</div>
		<div class="container">
			<br>
			<div class="row">
				<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
					<div style="min-width: 18rem;">
						<img src="{{product.image.url}}" alt="{{product.name}}">
					</div>
				</div>
				<div class="col-12 col-sm-12 col-md-12 col-lg-6">
					<div>
						<h1 class="my_prod_title">{{product.name}}</h1>
						<p>£{{product.price}}</p>
						<p class="my_title">Product Description</p>
						<p class="text-justify my_prod_text">{{product.description}}</p>
						{% if product.stock <= 0%}
							<p class="text-justify my_prod_text"><b>Out of Stock</b></p>
						{% else %}
							<a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}